/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить список всех бронирований (предстоящие встречи). Только для владельца. */
        get: operations["Bookings_list"];
        put?: never;
        /** @description Создать новое бронирование на свободный слот. Для гостя. */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить список всех типов событий. Доступно всем. */
        get: operations["EventTypes_list"];
        put?: never;
        /** @description Создать новый тип события. Только для владельца. */
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить тип события по ID. Доступно всем. */
        get: operations["EventTypes_get"];
        /** @description Обновить тип события. Только для владельца. */
        put: operations["EventTypes_update"];
        post?: never;
        /** @description Удалить тип события. Только для владельца. */
        delete: operations["EventTypes_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Получить свободные слоты для указанного типа события.
         *
         *     Если параметры `dateFrom` и `dateTo` не указаны, возвращаются слоты
         *     на ближайшие 14 дней от текущей даты.
         */
        get: operations["Slots_listAvailable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Бронирование встречи. */
        Booking: {
            /** @description Уникальный идентификатор бронирования. */
            id: string;
            /** @description Идентификатор типа события, на который создано бронирование. */
            eventTypeId: string;
            /** @description Имя гостя. */
            guestName: string;
            /** @description Email гостя. */
            guestEmail: string;
            /**
             * Format: date-time
             * @description Начало встречи (UTC).
             */
            startTime: string;
            /**
             * Format: date-time
             * @description Конец встречи (UTC).
             */
            endTime: string;
            /**
             * Format: date-time
             * @description Дата и время создания бронирования.
             */
            createdAt: string;
        };
        /** @description Запрос на создание бронирования. */
        BookingCreate: {
            /** @description Идентификатор типа события. */
            eventTypeId: string;
            /** @description Имя гостя. */
            guestName: string;
            /** @description Email гостя. */
            guestEmail: string;
            /**
             * Format: date-time
             * @description Начало встречи (UTC). Слот должен быть свободен.
             */
            startTime: string;
        };
        /** @description Тип события (вид встречи), создаваемый владельцем. */
        EventType: {
            /** @description Уникальный идентификатор типа события. */
            id: string;
            /** @description Название типа события (например, «Консультация»). */
            title: string;
            /** @description Описание типа события. */
            description?: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах.
             */
            durationMinutes: number;
        };
        /** @description Запрос на создание типа события. */
        EventTypeCreate: {
            /** @description Название типа события. */
            title: string;
            /** @description Описание типа события. */
            description?: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах.
             */
            durationMinutes: number;
        };
        /** @description Запрос на обновление типа события. Все поля опциональны. */
        EventTypeUpdate: {
            /** @description Название типа события. */
            title?: string;
            /** @description Описание типа события. */
            description?: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах.
             */
            durationMinutes?: number;
        };
        /** @description Временной слот, доступный для бронирования. */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота (UTC).
             */
            startTime: string;
            /**
             * Format: date-time
             * @description Конец слота (UTC).
             */
            endTime: string;
        };
        /** @description Параметры фильтрации слотов по дате. */
        SlotQueryParams: {
            /** @description Начало окна поиска (включительно, формат YYYY-MM-DD). */
            dateFrom?: string;
            /** @description Конец окна поиска (включительно, формат YYYY-MM-DD). */
            dateTo?: string;
        };
        /** @description Список доступных слотов. */
        SlotsResponse: {
            /** @description Массив доступных временных слотов. */
            slots: components["schemas"]["Slot"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Bookings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
        };
    };
    EventTypes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
        };
    };
    EventTypes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
        };
    };
    EventTypes_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Slots_listAvailable: {
        parameters: {
            query?: {
                dateFrom?: string;
                dateTo?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponse"];
                };
            };
        };
    };
}
